export const REQUEST_FACE = 'request-face'
export const RECEIVE_FACE = 'receive-face'
export const REQUEST_EMOTION = 'request-emotion'
export const RECEIVE_EMOTION = 'receive-emotion'
export const MOUNT_WEBCAM = 'mount-webcam'
